### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by lyolve** [AlexFlipnote/neofetch-win#16]
C:\Windows\system32>python -V
Python 3.6.5 :: Anaconda, Inc.

C:\Windows\system32>neofetch
Traceback (most recent call last):
  File "d:\program\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\program\Anaconda3\Scripts\neofetch.exe\__main__.py", line 7, in <module>
  File "d:\program\anaconda3\lib\site-packages\neofetch_win\main.py", line 63, in main
    shell()
  File "d:\program\anaconda3\lib\site-packages\neofetch_win\main.py", line 56, in shell
    nf.pretty_print(ignore_list=args.ignore),
  File "d:\program\anaconda3\lib\site-packages\neofetch_win\neofetch.py", line 236, in pretty_print
    components.append(*more_disk)
TypeError: append() takes exactly one argument (9 given)

**Comment by AlexFlipnote** [comment]
How many disks does your PC have?

**Comment by lyolve** [comment]
> How many disks does your PC have?

2 SSD + 1 HDD
CDE;
FG;
HIJK;

too much disks?

**Comment by AlexFlipnote** [comment]
Not really, just helps me find out what the error could be, and I see why it crashed, I'm bad at noticing how things can fail in time lmao. Will fix it asap

**Comment by AlexFlipnote** [comment]
There we go, this has now been fixed in 27bd3c5, update neofetch-win to 1.1.4 and see if it works now 😄

**Comment by lyolve** [comment]
It works now, seems that I forget to upgrade pip.
Thanks~

**Comment by AlexFlipnote** [comment]
Glad it worked out for you ❤️
