### ISSUE TITLE
No module named colorama

### ISSUE THREAD

**Issue by Sven65** [AlexFlipnote/neofetch-win#2]
Installed using `pip3.6 install neofetch-win`

getting error:

```py
Traceback (most recent call last):
  File "C:\Users\Mackan\AppData\Local\Programs\Python\Python36\Scripts\neofetch-script.py", line 11, in <module>
    load_entry_point('neofetch-win==1.0.3', 'console_scripts', 'neofetch')()
  File "c:\users\mackan\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\mackan\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\users\mackan\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\users\mackan\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\mackan\appdata\local\programs\python\python36\lib\site-packages\neofetch_win\__init__.py", line 1, in <module>
    from .neofetch import Neofetch
  File "c:\users\mackan\appdata\local\programs\python\python36\lib\site-packages\neofetch_win\neofetch.py", line 1, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
```

**Comment by AlexFlipnote** [comment]
Fixed setup.py now 👌
