### ISSUE TITLE
no such file 'requirements.txt'

### ISSUE THREAD

**Issue by Sven65** [AlexFlipnote/neofetch-win#3]
```py
D:\temp>pip install neofetch-win
Collecting neofetch-win
  Downloading https://files.pythonhosted.org/packages/93/d6/365fbb17a44d6d9b9b50420f7f856a342490dc5f4cb4e79218bbfce85915/neofetch-win-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Mackan\AppData\Local\Temp\pip-install-7n24byo5\neofetch-win\setup.py", line 7, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by AlexFlipnote** [comment]
Fixed
