### ISSUE TITLE
No module named 'psutil'

### ISSUE THREAD

**Issue by Sven65** [AlexFlipnote/neofetch-win#4]
```py
Traceback (most recent call last):
  File "C:\Users\Mackan\AppData\Local\Programs\Python\Python37-32\Scripts\neofetch-script.py", line 11, in <module>
    load_entry_point('neofetch-win==1.0.6', 'console_scripts', 'neofetch')()
  File "c:\users\mackan\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\mackan\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "c:\users\mackan\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "c:\users\mackan\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\mackan\appdata\local\programs\python\python37-32\lib\site-packages\neofetch_win\__init__.py", line 1, in <module>
    from .neofetch import Neofetch
  File "c:\users\mackan\appdata\local\programs\python\python37-32\lib\site-packages\neofetch_win\neofetch.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

**Comment by AlexFlipnote** [comment]
Please install python-dev

**Comment by AlexFlipnote** [comment]
Fixed with requirements.txt instead
