### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by HelloGwkki** [AlexFlipnote/neofetch-win#8]
Oops, I have to come up with a new ISSUE ...
This also shows that there is an error:sob:
Here's another mistake.
This error only appears on GIT BASH
`OvO $  neofetch
OSTraceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Scripts\neofetch-script.py", line 11, in <module>
    load_entry_point('neofetch-win==1.1.0', 'console_scripts', 'neofetch')()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\neofetch_win\main.py", line 59, in main
    shell()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\neofetch_win\main.py", line 54, in shell
    print(nf.pretty_print(), file=nf.stream)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'gbk' codec can't encode character '\ucf62' in position 12: illegal multibyte sequence
`
But works fine on CMD

**Comment by HelloGwkki** [comment]
:dog:

**Comment by AlexFlipnote** [comment]
This error seems to be an issue from https://github.com/tartley/colorama which `neofetch_win` uses for colours in CMD. Please make an issue to them about this, thanks ❤️
